export interface Meter {
  id: string,
  deviceZone: string,
  deviceId: string,
  serialNo: string,
  slaveId: string,
  modelSpec: string, 
  lineVoltage: string,
  lineFrequency: string,
  lineCurrent: string,
  lineActiveEnergy: string,
  activePower: string,
  activeEnergy: string,
  contractId: string,
  meterState: string,
  updateDatetime: string,
  updateStateDatetime: string,
  meterStateAdmin: string,
  updateStateAdminDatetime: string,
  shopName: string,
  custName: string,
  boothId: string
}
