export interface Ticket {
  CATEGORY: string,
  STATUS: string,
  DUE_DATE:string,
  CREATE_DATE:string,
  LOG:string,
  HEADLINE: string,
  CURRENT_HANDLER_USER_ID:string,
  TICKET_ID: string,
  DETAIL: string,
  OPENER_USER_ID: string,
  CONTRACT_NO: string,
  METER: string,
  id: string,
}
