const shopData = 
  [
    {   id: "113YpsnQr8b0hJOE9BmD", 
        uid: "owBleiElxAgfxet77qZEACHiwsX2",
        storeId:"A017",
        custName: "fvl013",
        custPhone: "",  
        contractNo: "",
        contractDate: "",  
        contractEndDate: "",
        boothName: "Gon express",
        boothCate: "",
        boothCode: "",
        boothZone: "",
    },
    {   id: "5pRN4eXwI19Z1okffhG4", 
        uid: "5SNtvoUpdBf8NP9jO6iX9b45Chn2", 
        storeId:"A011,A012",
        custName: "fvl008" , 
        custPhone: "",
        contractNo: "",
        contractDate: "",
        contractEndDate: "",
        boothName: "แป้งดำ",
        boothCate: "",
        boothCode: "",
        boothZone: "",
    },
    {   id: "7LF2PwdiPgkiS5sIZKU8", 
        uid: "U5VwQRjTJPbsEKhgZ2ZmgWp6OnY2",
        storeId:"A025",
        custName: "fvl019",
        custPhone: "", 
        contractNo: "",
        contractDate: "",
        contractEndDate: "",
        boothName: "SALA GARTI ศาลากะทิ",
        boothCate: "",
        boothCode: "",
        boothZone: "",
    },
   
];


export { shopData as shopData };
